" GENERAL SETTINGS
let maplocalleader=","
let mapleader=" "
set viminfo+=n~/.vim/.viminfo
set nocompatible
set autoindent
set textwidth=120

" Numbers, colors and cursors
syntax on
colorscheme nord
set termguicolors
set number
set wrap
set relativenumber
set scrolloff=99
set mouse=a
set fileencoding=UTF-8
set fileencodings=UTF-8

" Tab and search completion in the vim terminal
set hlsearch
set incsearch
set showcmd
set showmatch
set wildmenu
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set undofile
 
" Split preferences 
set splitright
set splitbelow

" Statusline ------------------------------------------ {{{
function! GitStatus()
  let [a,m,r] = GitGutterGetHunkSummary()
  return printf('+%d ~%d -%d', a, m, r)
endfunction

set statusline=
set statusline+=\ %F\ %M\ %Y\ %R
set statusline+=%=
set statusline+=git:\ %{GitStatus()}
set statusline+=\ hex:\ 0x%B\ row:\ %l\ col:\ %c\ 
set laststatus=2
" }}}

" Mappings ----------------------------------{{{
nnoremap - ddp 
nnoremap _ ddkP 
nnoremap <leader>cn  :edit $MYVIMRC<cr> 
nnoremap <leader>cnh :split $MYVIMRC<cr> 
nnoremap <leader>cnv :vsplit $MYVIMRC<cr> 
nnoremap <leader>scn :source $MYVIMRC<cr>
nnoremap <C-D> :term<CR>
nnoremap <leader>n :NERDTreeToggle<cr>
nnoremap <leader>w <C-W>w
inoremap jj <esc>

"Wrappings - ", ', (, [, {
nnoremap <leader>" viw<esc>a"<esc>bi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>bi'<esc>lel
nnoremap <leader>( viw<esc>a)<esc>bi(<esc>lel
nnoremap <leader>[ viw<esc>a]<esc>bi[<esc>lel
nnoremap <leader>{ viw<esc>a}<esc>bi{<esc>lel

" ipython-shell
nnoremap <localleader>ss :call StartPyShell()<CR>
noremap <localleader>sk :call StopPyShell()<CR>
" code execution
nnoremap <leader>r :call PyShellSendLine()<CR>
vnoremap <leader>r :call PyShellSendLine()<CR>
" LSP config
nnoremap <leader>dd :LspDefinition<cr>
nnoremap <leader>dn :LspNextDiagnostic<cr>
nnoremap <leader>dp :LspPreviousDiagnostic<cr>
nnoremap <leader>df :LspReferences<cr>
nnoremap <leader>dr :LspRename<cr>
nnoremap <leader>ds :LspStopServer<cr>
nnoremap <leader>dp :LspPeekDefinition<cr>
nnoremap <leader>da :LspCodeAction<cr>
nnoremap <leader>dh :LspHover<cr>
nnoremap <leader>df :LspDocumentFormat<cr> 
nnoremap <leader>dd :LspDefinition<cr>
"}}}

" Filetype Specific settings ----------------------{{{
augroup filetype_javascript
	autocmd!
	autocmd FileType javascript nnoremap <buffer> <localleader>c I//<esc>
augroup END

augroup filetype_python
	autocmd!
	autocmd FileType python vnoremap <buffer> <localleader>c :s/^/#/<CR>gv
	autocmd FileType python vnoremap <buffer> <localleader>u :s/^#//<CR>gv
augroup END
" }}}

" Vimscripts and file settings ----------------------------{{{
augroup filetype_vim
	autocmd!
	autocmd FileType vim setlocal foldmethod=marker
augroup END

nnoremap <leader>f :call FoldColumnToggle()<cr>
function! FoldColumnToggle()
	if &foldcolumn
		setlocal foldcolumn=0
	else
		setlocal foldcolumn=2
	endif
endfunction

nnoremap <leader>q :call QuickfixToggle()<cr>
let g:quickfix_is_open = 0

function! QuickfixToggle()
	if g:quickfix_is_open
		cclose
		let g:quickfix_is_open = 0
		execute g:quickfix_return_to_window . "wincmd w"
	else
		let g:quickfix_return_to_window = winnr()
		copen
		let g:quickfix_is_open = 1
	endif
endfunction

"}}}

" Vim plug plug-ins ----------------------------------------{{{
call plug#begin()

Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'scrooloose/nerdtree'
Plug 'airblade/vim-gitgutter'
Plug 'flazz/vim-colorschemes'
Plug 'benmills/vimux'
Plug 'greghor/vim-pyShell'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'mhinz/vim-startify'

call plug#end() 

function! s:on_lsp_buffer_enabled() abort
	setlocal omnifunc=lsp#complete
endfunction

augroup lsp_install
	au!
	autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

augroup nerd_tree
	au!
	autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
augroup END

" GitGutterColors
highlight GitGutterAdd    guifg=#00FF00 ctermfg=2 
highlight GitGutterChange guifg=#FFFF00 ctermfg=3  
highlight GitGutterDelete guifg=#FF0000 ctermfg=1

"}}}
